2014:
  Año_Nuevo: 2014/01/01
  Viernes_Santo: 2014/04/18
  Sábado_Santo: 2014/04/19
  Día_Nacional_del_Trabajo: 2014/05/01
  Día_de_las_Glorias_Navales: 2014/05/21
  San_Pedro_y_San_Pablo: 2014/06/29
  Día_de_la_Virgen_del_Carmen: 2014/08/15
  Independencia_Nacional: 2014/09/18
  Día_de_las_Glorias_del_Ejército: 2014/09/19
  Encuentro_de_Dos_Mundos: 2014/10/12
  Día_de_las_Iglesias_Evangélicas_y_Protestantes: 2014/10/31
  Día_de_Todos_los_Santos: 2014/11/01
  Inmaculada_Concepción: 2014/12/08
  Navidad: 2014/12/25
2015:
  Año_Nuevo: 2015/01/01
  Viernes_Santo: 2015/04/03
  Sábado_Santo: 2015/04/04
  Día_Nacional_del_Trabajo: 2015/05/01
  Día_de_las_Glorias_Navales: 2015/05/21
  San_Pedro_y_San_Pablo: 2015/06/29
  Día_de_la_Virgen_del_Carmen: 2015/08/15
  Independencia_Nacional: 2015/09/18
  Día_de_las_Glorias_del_Ejército: 2015/09/19
  Encuentro_de_Dos_Mundos: 2015/10/12
  Día_de_las_Iglesias_Evangélicas_y_Protestantes: 2015/10/31
  Día_de_Todos_los_Santos: 2015/11/01
  Inmaculada_Concepción: 2015/12/08
  Navidad: 2015/12/25